{{- if .Values.metallb.enabled }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: {{ .Values.metallb.namespace }}
  labels:
    app.kubernetes.io/name: metallb
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  addresses:
  - {{ .Values.metallb.network.ipRange.start }}-{{ .Values.metallb.network.ipRange.end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2advertisement
  namespace: {{ .Values.metallb.namespace }}
  labels:
    app.kubernetes.io/name: metallb
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ipAddressPools:
  - default-pool
{{- end }}

